# Generated by Django 5.0.6 on 2024-06-26 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='inscripcion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Principal.inscripcion'),
            preserve_default=False,
        ),
    ]
