# Generated by Django 5.0.6 on 2024-06-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_resultado_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='usuario',
        ),
    ]
